server.port=8080
spring.application.name=movie-streaming-platform

spring.datasource.url=jdbc:mysql://localhost:3306/movie_streaming_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Bangkok
spring.jpa.open-in-view=true

spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8
spring.sql.init.continue-on-error=false

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB

server.error.whitelabel.enabled=false
server.servlet.session.timeout=120m

app.upload-dir=uploads
app.deposit-payment-provider=SIMULATED_GATEWAY


# VNPAY configuration
app.payment.vnpay.enabled=true
app.payment.vnpay.tmn-code=TX9L9NNI
app.payment.vnpay.hash-secret=W178KREJGA6PGMWAD8HCIGYDI539LPX1
app.payment.vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
app.payment.vnpay.return-url=https://vaughn-unmigrative-monthly.ngrok-free.dev/payment/vnpay/return
app.payment.vnpay.locale=vn
app.payment.vnpay.order-type=other
app.payment.vnpay.expire-minutes=15

# Optional fallback for old simulated flow
